Store r.tableID also when fwmark rule is already present
NordSecurity/nordvpn-linux pull request #174
Opened 2023-11-21 07:09 UTC by piotrjurkiewicz

When fwmark rule already exists in the system, `r.tableID` is not set to the actual table ID. Instead it stays initialized to `0`, which means that new routes are then added to the `main` table instead of table `205` (or any custom table).

This pull requests changes `checkFwmarkRule` function to `findFwmarkRule`. It will check if fwmark rule already exist and return its table ID. This table ID is than stored in `r.tableID`.

2023-11-21 08:58 UTC, mariusSincovici commented on daemon/routes/iprule/iprule.go
> +func findFwmarkRule(fwMarkVal uint32, ipv6 bool) (bool, uint, error) {
Is the boolean needed, because when is false it also returns error?

2023-11-21 08:58 UTC, mariusSincovici commented on daemon/routes/iprule/iprule.go
> +	return false, 0, nil
It might be better to return some custom created error in this case, e.g. `not found`, and the caller to check the error type and decide what to do?

2023-11-21 10:36 UTC, Savolro requested changes

2023-11-22 07:18 UTC, keliramu approved these changes

2023-11-22 09:21 UTC, Savolro approved these changes

2023-11-22 13:41 UTC, merged