(3/4) Convert libdrop transfer to our internal transfer
NordSecurity/nordvpn-linux pull request #179
Opened 2023-11-22 09:36 UTC by EmilijusS

This PR adds code to convert Libdrop transfer representation to our representation. The next PR will start to actually use this code.

2023-11-29 10:25 UTC, Savolro requested changes

2023-11-29 10:25 UTC, Savolro commented on fileshare/transfer.go
> +// Converts libdrop transfer representation to our own
Add a comment to remove this on v4

2023-11-30 13:17 UTC, bartoszWojciechO approved these changes

2023-12-01 07:20 UTC, Savolro approved these changes

2023-12-01 07:22 UTC, merged