(4/4) Use Libdrop storage
NordSecurity/nordvpn-linux pull request #180
Opened 2023-11-22 09:43 UTC by EmilijusS

2023-11-28 11:26 UTC, bartoszWojciechO commented on fileshare/event_manager.go
> +func updateTransferWithLiveData(transfer *pb.Transfer, liveTransfers map[string]*LiveTransfer) {
Doc string should start with function name.

2023-11-28 12:12 UTC, bartoszWojciechO commented on fileshare/event_manager.go
> +func updateTransferWithLiveData(transfer *pb.Transfer, liveTransfers map[string]*LiveTransfer) {
I'd change this function to return `*pb.Transfer`. It's not necessary  but assignment is more verbose/explicit.

2023-11-28 12:22 UTC, bartoszWojciechO commented on fileshare/storage/combined.go
> +	} else if !errors.Is(err, os.ErrNotExist) {
Let's also add logging for other errors.

2023-11-28 12:26 UTC, bartoszWojciechO approved these changes

2023-11-29 10:42 UTC, Savolro requested changes

2023-11-29 10:42 UTC, Savolro commented on fileshare/events.go
> +// These are unused at the moment
Commented code can be removed

2023-11-30 13:06 UTC, Savolro approved these changes

2023-11-30 13:13 UTC, merged