Remove autostart plug
NordSecurity/nordvpn-linux pull request #358
Opened 2024-04-11 09:16 UTC by bartoszWojciechO

2024-04-11 09:58 UTC, Savolro requested changes

2024-04-11 09:58 UTC, Savolro commented on internal/constants.go
> +	snapUserDataDir := os.Getenv("USER_DATA_COMMON")
Since this is snap specific, `SNAP_USER_COMMON` can be used dirrectly

2024-04-11 09:58 UTC, Savolro commented on cmd/norduser/main.go
> +	dataDir := os.Getenv("USER_DATA")
Since this is snap specific, `SNAP_USER_DATA` can be used dirrectly

2024-04-11 09:58 UTC, Savolro commented on snap/snapcraft.yaml
> +      USER_DATA: $SNAP_USER_DATA
I think these can be removed

2024-04-11 11:33 UTC, Savolro requested changes
`snapconf.InterfaceNorduserAutostart` and its references need to be removed as well.

2024-04-11 13:09 UTC, keliramu approved these changes

2024-04-12 06:12 UTC, Savolro approved these changes

2024-04-16 09:50 UTC, merged